# cluster/apps/traefik/traefik-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: flux-system
      version: "10.24.0" # Replace with the latest version
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml