# Domum/cluster/apps/traefik/traefik-values.yaml
deployment:
  replicas: 1
service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: default
ports:
  web:
    port: 80
  websecure:
    port: 443