overlay:
  image: siderolabs/sbc-raspberrypi:v0.1.3 
  name: rpi_generic
  options:
    configTxt: |
      gpu_mem=32
      hdmi_safe=1  # Corrected syntax for HDMI safe mode
      kernel=u-boot.bin
      arm_64bit=1
      arm_boost=1
      enable_uart=1
      dtoverlay=disable-bt
      dtoverlay=disable-wifi
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/util-linux-tools
      - siderolabs/iscsi-tools