#Domum/cluster/apps/longhorn/longhorn-app.yaml
apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  labels:
    app: longhorn-ui
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: longhorn-ui