#cluster/metallb/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - namespace.yaml
  - metallb-deployment.yaml
  - metallb-config.yaml
  - rbac.yaml