# clusters/metallb/rbac.yaml

# ServiceAccount for MetalLB Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: metallb-system
  name: controller

---
# ServiceAccount for MetalLB Speaker
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: metallb-system
  name: speaker

---
# Role for MetalLB Controller
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metallb-system
  name: config-watcher
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding for MetalLB Controller and Speaker
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: metallb-system
  name: config-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-watcher
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system

---
# ClusterRole for MetalLB Speaker to manage nodes (Layer2 protocol)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-speaker
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "update"]

---
# ClusterRoleBinding for MetalLB Speaker
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-speaker
subjects:
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system