#clusters/metallb/rbac.yaml
# ServiceAccount for MetalLB Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: metallb-system
  name: controller

---
# ServiceAccount for MetalLB Speaker
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: metallb-system
  name: speaker

---
# Role for MetalLB Controller
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metallb-system
  name: config-watcher
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding for MetalLB Controller
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: metallb-system
  name: config-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-watcher
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system