# cluster/core/02-longhorn/ingress.yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.lan.digitalcactus.cc`)
      kind: Rule
      services:
        - name: longhorn-frontend  # <- Correct service name
          port: 80
          namespace: longhorn-system
      middlewares:
        - name: default-headers
          namespace: default
  tls:
    secretName: lan-digitalcactus-cc-tls
