# cluster/core/02-longhorn/ingress.yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.lan.digitalcactus.cc`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: longhorn-frontend  
          port: 80
          namespace: longhorn-system
  tls:
    secretName: lan-digitalcactus-cc-tls