# cluster/apps/vault/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  interval: 5m
  values:
    global:
      tlsDisable: true  # Disable TLS for initial setup
    server:
      enabled: true
      ha:
        enabled: true
        replicas: 2  # Match your worker nodes
        raft:
          enabled: true
          setNodeId: true
      volumes:
        - name: raft
          persistentVolumeClaim:
            claimName: vault-raft
      volumeMounts:
        - mountPath: /vault/data
          name: raft
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: []  # Remove strict anti-affinity
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values: ["vault"]
                topologyKey: kubernetes.io/hostname