# cluster/apps/vault/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-raft
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi