#Domum/cluster/vault/vault-helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: 0.29.1 # Use the latest version - https://github.com/hashicorp/vault-helm/releases
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    ui:
      enabled: true 
    server:
      affinity: {}
      ha:
        enabled: false
      dev:
        enabled: false
      standalone:
        enabled: true
      extraEnvironmentVars:
        VAULT_LOG_LEVEL: "debug"

      # Use the integrated raft storage
      dataStorage:
        enabled: true
        storageClass: "standard"  
        accessMode: "ReadWriteOnce"
        size: "5Gi"

      # Service type. NodePort or LoadBalancer for external access if you prefer.
      serviceType: "ClusterIP"