# Domum/cluster/apps/kustomization-flux.yaml  
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: ./vault          
  prune: true
  sourceRef:
    kind: GitRepository
    name: domum-repo
    namespace: flux-system