apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: myhomepage:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80