#cluster/core/04-traefik/helmrepo.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-repo
  namespace: traefik
spec:
  interval: 1m0s
  url: https://traefik.github.io/charts

