# cluster/core/04-traefik/values-configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: traefik
data:
  values.yaml: |
    globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

    additionalArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"

    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirections:
          entrypoint:
            to: websecure
            priority: 10
      websecure:
        http3:
          enabled: true
        advertisedPort: 4443
        tls:
          enabled: true
          
    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
        allowCrossNamespace: true  
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: 10.0.1.200
      loadBalancerSourceRanges: []
      externalIPs: []